version: '3.8'

networks:
  pg-net:
    ipam:
      config:
        - subnet: 172.0.6.0/24

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres123
    networks:
      pg-net:
        ipv4_address: 172.0.6.10
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: adminer-ui
    restart: always
    networks:
      pg-net:
        ipv4_address: 172.0.6.11
    ports:
      - "8081:8080"
